### ISSUE TITLE
FR: Expand Skin Support for weather.wunderground (personal_api)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#10]
Marcel,

Thank you for considering this Feature Request.

If you didn't know already..... After Kodi and WU decided to disable the API key that was hard coded into the Weather Underground service and remove it from the Repo it has since then been released under a new branch on GitHub (personal_api) with support for a personal (and free) API key.

I use and love this weather service - it's so much better then Yahoo or OpenWeateher in my opinion.

If you are interested... GitHub source:

https://github.com/uNiversaI/weather.wunderground/tree/personal_api

Free Dev API Key Request:
http://www.wunderground.com/weather/api/

Note: suggest getting the "Anvil Plan" Developer plan/features for your API key if you move forward with this request.

Additional Items that would be nice to support in the skin:

WEEKEND, 36HOUR, ALERTS, and MAP info/display
TODAY & CURRENT (expand to include all available data returned from the service)

Also Note the following settings should be available in the side menu panel to adjust:

Location1id and Location1 thru 5
... and
<setting id="Zoom" label="32125" type="slider" option="int" range="1,100"  default="10"/>
<setting id="Animate" label="32126" type="bool" default="false"/>
<setting id="Weekend" label="32121" type="enum" lvalues="32122|32123|32124" default="0"/>
<setting type="sep"/>
<setting id="Debug" label="32120" type="bool" default="false"/>
## CURRENT

Current.Location
Current.Condition
Current.Temperature
Current.Wind
Current.WindDirection
Current.Humidity
Current.FeelsLike
Current.UVIndex
Current.DewPoint
Current.ConditionIcon
Current.FanartCode
## DAY [0-6]

Day%i.Title
Day%i.HighTemp
Day%i.LowTemp
Day%i.Outlook
Day%i.OutlookIcon
Day%i.FanartCode
## WEATHERPROVIDER

WeatherProvider
WeatherProviderLogo

---
## FORECAST

Forecast.IsFetched
Forecast.City
Forecast.State
Forecast.Country
Forecast.Updated
## CURRENT

Current.IsFetched
Current.LocalTime
Current.LocalDate
Current.WindDegree
Current.SolarRadiation
Current.Pressure
Current.Precipitation
Current.HeatIndex
Current.WindChill
Current.Visibility
Current.WindGust
## TODAY

Today.IsFetched
Today.Sunrise
Today.Sunset
Today.MoonPhase
Today.AvgHighTemperature
Today.AvgLowTemperature
Today.RecordHighTemperature
Today.RecordLowTemperature
Today.RecordHighYear
Today.RecordLowYear
## DAILY [1-10]

Daily.IsFetched
Daily.%i.LongDay
Daily.%i.ShortDay
Daily.%i.LongDate
Daily.%i.ShortDate
Daily.%i.Outlook
Daily.%i.OutlookIcon
Daily.%i.FanartCode
Daily.%i.WindSpeed
Daily.%i.MaxWind
Daily.%i.WindDirection
Daily.%i.ShortWindDirection
Daily.%i.WindDegree
Daily.%i.Humidity
Daily.%i.MinHumidity
Daily.%i.MaxHumidity
Daily.%i.HighTemperature
Daily.%i.LowTemperature
Daily.%i.LongOutlookDay
Daily.%i.LongOutlookNight
Daily.%i.Precipitation
Daily.%i.Snow
Daily.%i.ChancePrecipitation
## WEEKEND [1-2]

Weekend.IsFetched
Weekend.%i.LongDay
Weekend.%i.ShortDay
Weekend.%i.LongDate
Weekend.%i.ShortDate
Weekend.%i.Outlook
Weekend.%i.OutlookIcon
Weekend.%i.FanartCode
Weekend.%i.WindSpeed
Weekend.%i.MaxWind
Weekend.%i.WindDirection
Weekend.%i.ShortWindDirection
Weekend.%i.WindDegree
Weekend.%i.Humidity
Weekend.%i.MinHumidity
Weekend.%i.MaxHumidity
Weekend.%i.HighTemperature
Weekend.%i.LowTemperature
Weekend.%i.LongOutlookDay
Weekend.%i.LongOutlookNight
Weekend.%i.Precipitation
Weekend.%i.Snow
Weekend.%i.ChancePrecipitation
## 36HOUR [1-3]

36Hour.IsFetched
36Hour.%i.Forecast
36Hour.%i.TemperatureHeading
36Hour.%i.Temperature
36Hour.%i.Heading
36Hour.%i.ChancePrecipitation
36Hour.%i.OutlookIcon
36Hour.%i.FanartCode
## HOURLY [1-36]

Hourly.IsFetched
Hourly.%i.Time
Hourly.%i.ShortDate
Hourly.%i.LongDate
Hourly.%i.Temperature
Hourly.%i.DewPoint
Hourly.%i.FeelsLike
Hourly.%i.Precipitation
Hourly.%i.Snow
Hourly.%i.HeatIndex
Hourly.%i.WindChill
Hourly.%i.Mslp
Hourly.%i.WindSpeed
Hourly.%i.WindDirection
Hourly.%i.ShortWindDirection
Hourly.%i.WindDegree
Hourly.%i.Humidity
Hourly.%i.UVIndex
Hourly.%i.ChancePrecipitation
Hourly.%i.Outlook
Hourly.%i.OutlookIcon
Hourly.%i.FanartCode
## ALERTS [1-<number of alerts>]

Alerts.IsFetched
Alerts.%i.Description
Alerts.%i.Message
Alerts.%i.StartDate
Alerts.%i.EndDate
Alerts.%i.Significance
Alerts.RSS
Alerts
Alerts.Count

[MAP]
Map.IsFetched
MapPath

Thanks again for the consideration :)

**Comment by marcelveldt** [comment]
weather underground is already working with the skin, including maps and alerts.
What is it exactly that you're still missing and should be added to the skin ?

**Comment by mgonzales71** [comment]
I don't see a map displayed on my system:

![kyxarqe 1](https://cloud.githubusercontent.com/assets/6510026/6314206/75c6224a-b98a-11e4-8264-4d3466108ef3.jpg)

 - is there an option to enable it?

this is what I see in my side menu - I could have sworn I saw another option/options there once 

![7lhii43 1](https://cloud.githubusercontent.com/assets/6510026/6314218/246dedd2-b98b-11e4-85cb-904a24f823f6.jpg)

**Comment by marcelveldt** [comment]
maps should display automatically once they're available...
the only thing taht I didn't have time to add yet is the 36hour and weekend forecasts, they're kinda low on my prio list because you already have the overview, 10 day forecast and the hourly forecast.

If really needed I can see if I can add them too.

I think with the sideblade you're referring to the multiple locations ?
Didn't add them too because you're able to toggle between locations with the location toggle/button already. Offcourse, if needed it shouldn't be too hard to add it in.

The maps are working in my case but it will only display US locations, nothing outside the US. Think it's like that by design.

**Comment by mgonzales71** [comment]
this is what i see in confluence btw..

![ijcqo0d 1](https://cloud.githubusercontent.com/assets/6510026/6314329/7b105838-b98f-11e4-8239-e8740beef0db.png)

regarding maps... If I switch to openweathermap I see the maps and oddly if I switch back to weather underground after I had switched to Weather Underground the maps stay - but I haven't see the maps appear leaving weather underground selected from a fresh start of the app. odd right?

as you can see here:

![o5plkkx 1](https://cloud.githubusercontent.com/assets/6510026/6314339/12bff9a4-b990-11e4-9156-a63baa2b0d82.jpg)


btw - if you do work on this further a tab to display the weather alert text would be cool too (like in confluence above)

I love the tabs being moved from the side menu like you have done - make so much more sense,

thanks again for the work on this - but make it low priority

**Comment by mgonzales71** [comment]
This works now with the latest updates by ronnie to Weather Underground.

Titan displays these menus now:
![2016-02-28_08-07-55](https://cloud.githubusercontent.com/assets/6510026/13380211/75372422-ddf2-11e5-96a6-9e1342d15e4e.png)

Think only the 36 hour item is missing but really not a big deal for me.

prob ok to close now.
