### ISSUE TITLE
switch button does not work

### ISSUE THREAD

**Issue by madStEvil** [marcelveldt/skin.titan#102]
for exampe try to change the view in the options menu,
or in the Skin-Settings the Background overlay texture
Other are also affected.

pls check!

and thx, for the beautiful skin :)

**Comment by marcelveldt** [comment]
I think something is wrong with your setup because that should all work.
What version of the skin are you using ?

**Comment by madStEvil** [comment]
hmm, i use the helix skin from your current master repository. I zipped the folder and installed it via kodi... correct? if i install the older version from the official kodi repo it worked!
Maybe i have to delete some old config file or something else? reset skin properties doesn't helped.
which files i have to delete for a complete uninstall?

thanks for your help!

**Comment by marcelveldt** [comment]
Please do not use the version from github because it will contain errors and I will not support it.
Use the version from official repo OR use the beta version from the beta repo (hosted at Emby).

**Comment by madStEvil** [comment]
ok thx i will try the beta repo...no problem.
Very good project, Keep it up!

but one request i have to you:
increase the max lines in guide (timeline) from 10 to 12 would be very nice!! but it has time... ;-)

good luck!
