### ISSUE TITLE
weather on slim OSD

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#127]
http://forum.kodi.tv/showthread.php?tid=231000&pid=2073125#pid2073125

**Comment by mgonzales71** [comment]
done - see PR - https://github.com/marcelveldt/skin.titan/pull/131

based mod/changes off latest skin xml code on GIT with the new helper script have not been able to test latest skin with latest helper script yet (seem to not be fully integrated yet ie addon.xml still references old helper, etc)

**Comment by marcelveldt** [comment]
Hi Mario, thanks!
I am fully rewriting parts of the skin. I will checkin what I have to Git in a bit.

**Comment by marcelveldt** [comment]
thanks for the PR. Current Git version should work pretty stable and has all changes included for the new skinhelper.

If you want to test, please install the latest skinhelper script from Github and also the latest version of skin.titan + helper script.

It *should* convert all your previous settings to the new settings. I have completely revamped the widget sections and skinshortcuts so I'm very curious if that will be migrated correctly as I've spent really some time with building a migration script.

**Comment by mgonzales71** [comment]
i tried it - here are my results...
https://github.com/marcelveldt/skin.titan/issues/133
