### ISSUE TITLE
4k codec indicator error

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#134]
this seems to be displayed in error?

![2015-09-03_23-22-42](https://cloud.githubusercontent.com/assets/6510026/9677782/f0bdc290-5292-11e5-9c9c-cfe43eb164f5.jpg)

from the log you can see this is not 4k video: 

22:41:19 T:10688  NOTICE: DVDPlayer: Opening: http://192.96.204.216:182/d/6g7uhzeyvle32chjj4dtvevf2h24wyo32fhstctngij6rfc2gjkem4kp/under.the.dome.312.hdtv-lol.mp4|Referer=http%3A%2F%2Fmrfile.me%2Fua57lfnt7rlh&User-Agent=Mozilla%2F5.0+%28Windows+NT+6.1%3B+rv%3A34.0%29+Gecko%2F20100101+Firefox%2F34.0
22:41:19 T:6380  NOTICE: Creating InputStream
22:41:19 T:6380  NOTICE: Creating Demuxer
22:41:22 T:6380  NOTICE: Opening stream: 0 source: 256
22:41:22 T:6380  NOTICE: Creating video codec with codec id: 28
22:41:22 T:6380  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
22:41:22 T:6380  NOTICE: Creating video thread
22:41:22 T:6380  NOTICE: Opening stream: 1 source: 256
22:41:22 T:6380  NOTICE: Finding audio codec for: 86018
22:41:22 T:2008  NOTICE: Thread DVDPlayerVideo start, auto delete: false
22:41:22 T:2008  NOTICE: running thread: video_thread
22:41:22 T:6380  NOTICE: Creating audio thread
22:41:22 T:2008  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(720x404)
22:41:22 T:11864  NOTICE: Thread DVDPlayerAudio start, auto delete: false
22:41:22 T:11864  NOTICE: running thread: CDVDPlayerAudio::Process()
22:41:22 T:11864  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)

**Comment by marcelveldt** [comment]
just fixed, thanks
