### ISSUE TITLE
missing views in...  (latest git copy of skin, helpers and helper)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#136]
missing views in...  video & music addons, videos and music

only presented with the following views to choose from:

![2015-09-05_12-52-22](https://cloud.githubusercontent.com/assets/6510026/9701047/1e6b0efa-53ce-11e5-8df7-a5e4c005db0d.png)

**Comment by marcelveldt** [comment]
It will only show views that are actually available for the content.

**Comment by mgonzales71** [comment]
i could have sworn more views were available in some of those areas.  maybe i need to take a nap ;)
been up all night (couldn't sleep).

oh... 

did you see the PR I sent that lets you see the cache buffer progress - think I remember reading you had issues with that and it not working for you a while back.  

I think I found a pretty decent solution. there is no color setting specifically for that progress control - wasn't sure if you wanted one or not.

as always feel free to adjust, etc as you like.

Mario

**Comment by mgonzales71** [comment]
think you can close this
