### ISSUE TITLE
resize nextup episode panel

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#139]
The current implementation of the nextup episode service is a bit overwhelming for some, it takes a large part of the screen.

Can it be resized ?

@mgonzales71 Is this something you're willing to pickup if you have any time ?

http://emby.media/community/index.php?/topic/9255-titan-skin/page-85#entry245005

**Comment by mgonzales71** [comment]
yes - it can be resized - but I squeezed it down to a graphic, plot, title, etc, a countdown timer and cancel button.

what size do you propose?  what info should be omitted/condensed?

i think you could create a skin setting and then create control groups with conditional visible statements 

two files used by the script: script-nextup-notification-NextUpInfo.xml and script-nextup-notification-StillWatchingInfo.xml

I would prefer a skin setting like:  use compact nextup notification dialogs (toggle on/off)

what do you think?
it could be as simple as a text countdown timer, next episode title, a "watch now" and "cancel" button.

**Comment by marcelveldt** [comment]
Yes, the settings would be nice. Maybe use the OSD panel layout for it so it has that size ?
And then add some visibility conditions to add the OSD panel when that nextup panel is active ?

**Comment by mgonzales71** [comment]
should be good to go with the latest update to the re-opened PR.
https://github.com/marcelveldt/skin.titan/pull/141

**Comment by mgonzales71** [comment]
think you can close this also
