### ISSUE TITLE
bug: phantom widgets where none defined

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#142]
don't know if this is a skin or helper script issue

have a home tile
it has no widgets assigned
but get a single panel ( which also happens to be the first item in my first home tiles widget)

![2015-09-13_12-08-53](https://cloud.githubusercontent.com/assets/6510026/9838352/b94e499e-5a10-11e5-94ad-33f126aff2e0.png)
![2015-09-13_12-08-12](https://cloud.githubusercontent.com/assets/6510026/9838353/b94e5664-5a10-11e5-8b7c-9bb13f97dedd.jpg)
![2015-09-13_12-08-20](https://cloud.githubusercontent.com/assets/6510026/9838354/b94fe3a8-5a10-11e5-9a7f-685ecbfc6ed2.jpg)

**Comment by mgonzales71** [comment]
issue also manifests for "single" box widget setting on home tiles with no widgets

![2015-09-13_12-23-12](https://cloud.githubusercontent.com/assets/6510026/9838435/78b4a43a-5a12-11e5-8622-1749ffb25b7a.jpg)

**Comment by marcelveldt** [comment]
thanks for the catch, it should now be fixed.
