### ISSUE TITLE
sideblade unfocused buttons sometimes not visible (revisit)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#145]
not high priority or anything but ran into a reason to revisit an old issue (https://github.com/marcelveldt/skin.titan/issues/107): sideblade menu and hard coded color choices that don't follow user theme color choices can end up making things look wrong/bad....

Personally I think hard coding color choices will eventually lead to conditions that the user will have no ability to resolve.  

for instance I was playing around with color settings and ran into an issue (this one) that highlights why all elements should be consistent unless it is imperative that it not be....

setting general panel color to ffffff with 15% transparency:

![2015-09-28_00-45-46](https://cloud.githubusercontent.com/assets/6510026/10130260/b391df0e-657b-11e5-8d19-22a249c98816.png)

what the side blade menu that ignores transparency setting of the panel color and also ignores button color ends up looking like:

![2015-09-28_00-46-01](https://cloud.githubusercontent.com/assets/6510026/10130259/b391d59a-657b-11e5-87db-528359ac009d.png)

my opinion is to follow the user settings (again if they want to make horrible choices let them :smile:) or to give the user options for side blade color settings.

a saying my dad has - "give them all the rope they want but if they end up hanging themselves with it - that is on them not me."

what is your thinking on this?  again not high priority but would like to revisit and reconsider it when you have time.  thanks Marcel!

**Comment by mgonzales71** [comment]
also setting general panel color to: None

produces a few other cosmetic issues:

![2015-09-28_01-17-05](https://cloud.githubusercontent.com/assets/6510026/10130657/267f1c7c-657f-11e5-9fdc-d0ad4de80f3c.png)
![2015-09-28_01-17-18](https://cloud.githubusercontent.com/assets/6510026/10130659/267fef4e-657f-11e5-9146-d3ea0429c602.png)
![2015-09-28_01-17-27](https://cloud.githubusercontent.com/assets/6510026/10130658/267f4b3e-657f-11e5-852e-00fc7681ff3e.png)

**Comment by marcelveldt** [comment]
The only REAL solution to this is to have an extra color setting for the sideblade/options panel..

**Comment by mgonzales71** [comment]
I not against that as a solution - just thought it would be easier to adopt the existing settings - either way it resolves color settings colliding with coded colors - thanks for pondering on this again 
:smile:

**Comment by marcelveldt** [comment]
adopting the existing settings is not an option... the sideblade/options menus are rendered on top of the existing content. If you have set a transparency then the text will be completely unreadable. I will go ahead and add two more color settings: color for the panel itself and for the submenu buttons

**Comment by marcelveldt** [comment]
fix for color set to None is now also on git.
