### ISSUE TITLE
FR: Add support for infolines

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#146]
support for infolines in the maninmenu and videonav with total watched/unwatched etc.

http://forum.kodi.tv/showthread.php?tid=205482&pid=2122364#pid2122364

**Comment by marcelveldt** [comment]
total watched/unwatched is available as of isengard

**Comment by marcelveldt** [comment]
added support for infolines to the skin.

@vdb86 this means that this option will also allow you to disable the infoline in the header.
Available in next beta

**Comment by vdb86** [comment]
Sounds good, looking forward to testing next beta!
