### ISSUE TITLE
1 row small tiles + vertial submenu broken

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#162]
can't access submenu or widgets with this configuration
on jarvis running latest git master copy of skin + latest helper

**Comment by mgonzales71** [comment]
also tried with horizontal sub menus - you can get to the submenu but not widgets still.
---- not sure that 1 row small + vertical sub is a valid combo even.

all see in the log file is the following error when trying to go "up" to the widgets:

23:48:22 T:17516   ERROR: Keymapping error: no such action '' defined
23:48:22 T:7880   ERROR: Previous line repeats 1 times.
23:48:22 T:17516   ERROR: Keymapping error: no such action '' defined

**Comment by mgonzales71** [comment]
just realized I didn't have debug on... here is better error message:

23:53:33 T:17516   DEBUG: Keyboard: scancode: 0x48, sym: 0x0111, unicode: 0x0000, modifier: 0x0
23:53:33 T:17516   DEBUG: CInputManager::OnKey: up (0xf080) pressed, action is Up
23:53:33 T:17516   ERROR: Keymapping error: no such action '' defined
23:53:33 T:17516   DEBUG: CApplication::ExecuteXBMCAction: Tried translating, but failed to understand $VAR[HomeButtonUpAction]

**Comment by mgonzales71** [comment]
ok even more odd.. if I choose 1 row + large tiles - vertical is no longer an option for submenu.

I know that its a GIT copy but you know me - I am always testing, testing, testing looking for bugs for you when I can hehe

![2015-12-04_00-01-30](https://cloud.githubusercontent.com/assets/6510026/11584667/760010ec-9a1a-11e5-8ce2-6c142c3548bb.png)


btw you have kids right?  do they like the snow? :smile:

**Comment by marcelveldt** [comment]
Thanks for the catch Mario, it should now be fixed on Git.

BTW: vertical submenu is not available for small tiles, the bug was that it was the other way around now ;-)

Can you give the latest Git a try ?

Oh and yes I have a daughter but she is only 6 months old :-)

**Comment by mgonzales71** [comment]
oh well - a new father - congrats to the new parents! :baby_bottle: hehe

going to grab git copy to test now

**Comment by marcelveldt** [comment]
tnx :-)

Wait a few minutes, I'm about to checkin a lot more changes

**Comment by marcelveldt** [comment]
done, both skinhelper and titan now checked in latest changes.

**Comment by mgonzales71** [comment]
ok I have checked the latest (grabbed about 20 mins ago)
works now.

although - it showed I had vertical submenu (see pic below, also they didn't work) but once I changed them to horizontal text they worked fine.

Hey - Question - can you allow custom path for weather fanart again for Jarvis?

I tried to build a multi weather fanart resource package to use instead of the repo version and it doesn't seem to want to work right - some images display, lots give errors in the log file.  

custom weather icon's I made work just fine.

try these custom icons out:
![preview](https://cloud.githubusercontent.com/assets/6510026/11598714/58e73734-9a78-11e5-9b95-aa7b7528b431.jpeg)

zip file: https://onedrive.live.com/redir.aspx?cid=599da6bd82779e65&resid=599DA6BD82779E65!6109&parId=599DA6BD82779E65!4605&authkey=!ADPzCuA8E97l9kQ&ithint=file%2czip


![2015-12-04_11-03-43](https://cloud.githubusercontent.com/assets/6510026/11598568/a00c3e94-9a77-11e5-947c-b26cb5c929e9.png)

**Comment by mgonzales71** [comment]
hey - give me your thoughts on this little project I have been playing around with.

https://github.com/mgonzales71/screensaver.skinnable

the basic concept is a screensaver "shell" that will allow skin devs to create a custom screensaver for their skin that can inherit features from the skin.

I have created custom files for use with Titan (Jarvis / master builds)

they are here: https://github.com/mgonzales71/screensaver.skinnable/tree/master/titan%20skin%20custom%20files

inherits header text and shadow color
uses skin selected weather icons
uses skin logo
displays snow if enabled in the skin
displays clock as a retro flip style display
displays random photos if defined ($INFO[Window(Home).Property(SkinHelper.PicturesBackground)])

screenshot...
![2015-12-04_12-03-15](https://cloud.githubusercontent.com/assets/6510026/11600063/34ea2d3a-9a7f-11e5-891b-7c15b3a1869b.jpg)

**Comment by mgonzales71** [comment]
and if (random) pictures not defined in skin / skin helper:

![2015-12-04_13-37-09](https://cloud.githubusercontent.com/assets/6510026/11602078/60134e3a-9a8c-11e5-92e4-c2b1663b2076.png)

**Comment by marcelveldt** [comment]
Mario,

The proper way should be to create a resource image addon.
Note that for large image packs you must not package them with a texture packer.
Maybe focus on getting the resource addon working ?

Also, nice work with the screensaver. Be carefull with your code btw, now it isn't unicode (special characters) safe.

For example, xbmc.translatePath(blah) should be: xbmc.translatePath(blah).decode("utf-8")

**Comment by mgonzales71** [comment]
Thanks for the info - Python is very very new to me.

Regarding image resource packs i found a thread on what seems to be the problem I am having... 

http://forum.kodi.tv/showthread.php?tid=240159

I will try again - but I'm starting to think that alternative names like resource.images.weatherfanart.multi.*  are not supported for multi weather fanart.

So there can only be one - it is maybe hard coded to only recognize one name?

**Comment by mgonzales71** [comment]
you can close this - haven't seen any problems with the various home layouts and this particular issue is fixed - thanks again!
