### ISSUE TITLE
multi weather image resource strangeness.

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#164]
saw your posts about this and replied myself:
http://forum.kodi.tv/showthread.php?tid=246245&pid=2180136#pid2180136

as you can see the skin finds the backgrounds but the widget do not:

![2015-12-06_19-01-39](https://cloud.githubusercontent.com/assets/6510026/11618150/f1b902a6-9c4b-11e5-85e9-fc72d259f507.jpg)
![2015-12-06_19-02-00](https://cloud.githubusercontent.com/assets/6510026/11618151/f1b9e3ba-9c4b-11e5-93aa-0343a09fa6fd.jpg)

**Comment by mgonzales71** [comment]
i can provide you with a zip of the image resource addon i am using if you like.

**Comment by marcelveldt** [comment]
Is this issue with a resource addon you created yourself or with one of the Kodi team ones ?

**Comment by mgonzales71** [comment]
Created myself - i saw your post about the helper having issues with the exact same error messages so I wonder if it was related.

I am can double check and redo my custom resource again tonight by reducing the number of images and then making sure they are all good image files.  I don't know maybe it's related to having too many included with the resource addon?  What was the resolution with respect to your posting with the same error messages?

**Comment by mgonzales71** [comment]
Forgot to ask if you know of another skin that is currently supporting Jarvis and the image resource fanart so I can test with an alternate skin.

Thanks!

**Comment by marcelveldt** [comment]
I think most Jarvis ready skins will support the resource image addons.

You did have .Multi in your addon name ?
The resource selector script sets a boolean that the addon is Multi-image
