### ISSUE TITLE
FR: Widget Row Location Option  (low priority)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#165]
LOW priority - but when using small home tiles / 1 row can there be an option to move the widgets higher as they usually are (to allow more view of the backgrounds) 

again low priority - thanks Marcel.

![2015-12-10_21-54-38](https://cloud.githubusercontent.com/assets/6510026/11736975/eb9f5218-9f88-11e5-8cee-eb820a024585.jpg)

**Comment by marcelveldt** [comment]
done...
