### ISSUE TITLE
auto replay of played streams via video addons at end of playback

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#170]
Hey Marcel...

Happy New Year! - hope all is going well for you!

got something for when you are bored LOL :smile:

the video link will better illustrate the issue

basically - have a video addon, adding / integrating streams of the tv shows to kodi library

choose to playback a tv episode stream via library
auto play stream via video addon works fine
at end of playback the item is re-launched for playback again
requiring the selection of cancel

link to video showing behaviour and also a debug enabled excerpt of the log for the event period

I have tried to replicate this in other skins like confluence, etc and the re-play does not happen.

not sure but maybe it is the way playback is called.. a dialog that is re-opened instead of closed after playback ends?

anyway - again low priority 

video link

https://onedrive.live.com/redir?resid=599DA6BD82779E65!6279&authkey=!AI02zkKuX4cUIjI&ithint=video%2cmp4

log link

https://onedrive.live.com/redir?resid=599DA6BD82779E65!6280&authkey=!ANR7aMFNaF157wQ&ithint=file%2clog

Thanks as always!

Mario

**Comment by marcelveldt** [comment]
Hi Mario, if this issue still exists, do you mind creating a card in Trello ?
