### ISSUE TITLE
PVR support for Jarvis

### ISSUE THREAD

**Issue by Glenn-1990** [marcelveldt/skin.titan#171]
Would it be possible to improve PVR support for Jarvis?

These are the problems that I encounter:
- In confluence, there is an "group timers" option in the timers window, this allows users to group timers per repeating timer rule. (Jarvis supports repeating timers now)
- Also in Jarvis there is a new column (in timers window) called "Type" which then shows "manual once", "repeating epg based", etc.
- When kiosk mode is enabled, it's not possible to enter the pvr sidebar anymore, only the settings from the sidebar should be hided?
- It would be nice to get a small tv screen next to the channels (in channel view) like confluence, also clicking on that tv screen will open the playing channel in fullscreen now with Jarvis.

**Comment by marcelveldt** [comment]
Yes, I will do so next week, thanks for reminding me.
From what I recall I still need to fix these PVR stuff and the new audioDSP stuff for Jarvis

**Comment by marcelveldt** [comment]
All remaining changes for Jarvis have been incorporated into the skin now, including the PVR changes.
I will push another beta version out later today and new stable version at Tuesday.

**Comment by Glenn-1990** [comment]
Ok thanks! :-)
