### ISSUE TITLE
Q: Forced Views - Exclusions possible?

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#172]
Is it possible to exclude a view of an addon from forced views?

Like  - maybe a toggle control in the side blade to exclude that particular view from being forced (when possible to do so)?

I love the option but I have a couple of add ons that when put in a paricular view look awful because the add on does not provide proper artwork for certain views.. or for instance "movie" is detected for a list in an addon that is not really movie data

don't know if it is even possible but figure I would at least ask.

Thanks!

Mario

**Comment by marcelveldt** [comment]
Hmmm, I'll have to think about this if this can be done the right way.

**Comment by mgonzales71** [comment]
no rush - just was curious - thanks :)
