### ISSUE TITLE
FR: New big vertical home layout

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#173]
**Simple confluence style homescreen vertical**

- Bigger font size (at least twice bigger) and maybe a bit more space between the items.
- Option to completely disable the logo, not just replace it with a custom image, that would provide more space for the vertical menu
- Possibility to disable zoom effect on a selected item and just change text color or area selection color.

Example screenshot:
http://i.imgur.com/8sYZssG.png

**Comment by marcelveldt** [comment]
added to the skin.

**Comment by vdb86** [comment]
Hi Marcel, I'm currently playing around with the new beta!
Tried the new big vertical menu, it looks awesome!
There is one issue with it, the weather is hidden behind the menu.

**Comment by vdb86** [comment]
I feel that the navigation animation should be faster, I'll play around with it.

**Comment by vdb86** [comment]
Tested it out with 2x animation, so time would be 150, looks less laggy.

**Comment by marcelveldt** [comment]
fixed the weather and changed animation speed, thanks for the feedback
