### ISSUE TITLE
FR: new big horizontal home layout

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#174]
**Simple confluence style homescreen horizontal**

- Wraparound effect
- Somewhat bigger font

Example screenshot:
http://i.imgur.com/kOoi52E.png

**Comment by marcelveldt** [comment]
@vdb86 

this is the first result of the new horizontal home...


![2016-02-11 2](https://cloud.githubusercontent.com/assets/6389780/12988987/822424ce-d103-11e5-9303-726ee56be616.png)

**Comment by vdb86** [comment]
It looks beautiful!

**Comment by marcelveldt** [comment]
OK great. It will be included in next beta skin update

**Comment by vdb86** [comment]
Just to check, does it just scroll through or it uses zoom effect too?

**Comment by marcelveldt** [comment]
I've added a little zoom effect. I will upload a new beta tomorrow so you can play with it.

**Comment by vdb86** [comment]
Sounds good!
