### ISSUE TITLE
FR: choose actor info mode

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#175]
Currently actor info is opened in extendedinfo by default while some users just want the "in library" collection list as it is by default in Kodi.

Add a setting to control the behaviour.

**Comment by vdb86** [comment]
The extendedinfo is well implemented, but it would be great to choose the behavior.
I personally like getting "in library" information instead of "global information".

**Comment by marcelveldt** [comment]
I've added a setting to control the behaviour of the cast list. Available in next beta
