### ISSUE TITLE
FR: Loginscreen enhancements

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#176]
Add an option to remove last login information
Add a power button (in a corner) which just exits Kodi
Maybe change the aspect ratio of Profile pictures

**Comment by vdb86** [comment]
If possible disable access to profile editing from Loginscreen.
Currently pressing "C" shows a side menu with Edit Profile.

**Comment by marcelveldt** [comment]
I'm not sure that an option can be added to remove the last login info because the setting is userbased. The loginscreen is not userbased so that setting will not apply. Is is really important to hide it ?

picture aspect and power button is no problem

**Comment by vdb86** [comment]
As far as I remember showing information for last login is just a skin option.
If I remember correctly removing <label>$INFO[ListItem.Label2]</label> from LoginScreen.xml does the job.
In order for everything to look pretty the Name of the profile should be centered.

**Comment by marcelveldt** [comment]
Yeah I know I can remove label2 but what if users do actually want that info to be displayed ?

**Comment by vdb86** [comment]
If I understand you correctly loginscreen doesn't check the user settings at all?
I'd definitely like to hide it, now it's just more complicated than I originally thought.

**Comment by marcelveldt** [comment]
Hmm, maybe it will work and it will take the setting from the master profile. I'll take a look at it

**Comment by vdb86** [comment]
Sounds good!

**Comment by marcelveldt** [comment]
yep, does indeed take the setting from master profile so it should be fine after all

**Comment by marcelveldt** [comment]
endresult (with setting enabled to hide the login info)

![2016-02-13](https://cloud.githubusercontent.com/assets/6389780/13030010/97372d80-d29c-11e5-8b96-38a56673a12f.png)

**Comment by vdb86** [comment]
I'm glad that worked!
That's freaking awesome...
Quick question, any way to disable context menu here?
Basically if someone presses C on some profile a side menu opens with Edit Profile.

**Comment by marcelveldt** [comment]
yep, I'm testing that now too.

**Comment by marcelveldt** [comment]
![2016-02-13 1](https://cloud.githubusercontent.com/assets/6389780/13030053/ab10182a-d29d-11e5-963d-72843630d042.png)

**Comment by marcelveldt** [comment]
OK, fixed. Available in next beta ;-)
I'll see if I can crunch a few more little fixes and then I'll go ahead and build the new beta so you can give it a spin.

I closed the Git issues for my own oversight but you can reopen them if you have any comments after testing

**Comment by vdb86** [comment]
This is pretty sweet, glad you managed to set it up!
I've spent a lot of time with xbmc/Kodi, this is the best skin, not because of it's features, but because of you...

**Comment by vdb86** [comment]
All of this is awesome!
I was thinking about having the power button exiting Kodi straight up, but I like how you implemented the current one.
Any chance to choose the behavior between the current behavior and direct exiting Kodi?

**Comment by marcelveldt** [comment]
it lists all available power options. So, if shutdown is disabled in Kodi settings or the system can't shutdown (e.g. on android) it will only quit when you press the button

**Comment by vdb86** [comment]
I see!
Not sure how to disable shutdown in settings, I know we can choose the behavior.
Nevertheless, so on Android for example, when you press the power button it won't show the menu, it will just exit Kodi?
