### ISSUE TITLE
Choosing button visibility

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#178]
It would be great if we could choose visibility of some buttons in movie information window.
Basically having an option for these buttons:
-Trailer
-YouTube Trailer
-Cast
-Similar
-Extended Info
-My Rating
-Choose Art
-Refresh
-Show Disc Art
-Hide Panel Background

**Comment by mgonzales71** [comment]
hmm - could be my lack of sleep (its late, now early here) but I am curious as to why?  
My first thought when I read this is why have a setting to enable/disable views of settings?

**Comment by vdb86** [comment]
Some users prefer different combinations of setting in info window.
For example I use only trailer, cast and refresh (when needed), I have absolutely no need for YouTube, Similar, Extended info and the rest.
On the other hand if a user goes somewhere where he has limited (or expensive) internet access, and has everything already set up for offline use (local trailer, subtitle, actor images, etc), buttons like YouTube and Extended Info complicate things.

**Comment by marcelveldt** [comment]
OK, I've added an option to select which buttons should be shown. Available in next beta

**Comment by vdb86** [comment]
Looks good and works perfectly!
It seems that you have missed My Rating button.
Similar and extended info act like one button, similar button is dictating visibility of extended info, they are both either visible or not.
Except for that I'm absolutely loving this!

**Comment by marcelveldt** [comment]
Oh, right. I codec this support in Isengard and merged it into the jarvis branch. Missed that my rating button as it is included in jarvis only. Will fix it and the similar/extended buttons too..

**Comment by vdb86** [comment]
Sounds good!
Thank you for these features...

**Comment by vdb86** [comment]
Hi Marcel,
in the settings My Rating button is named: Dynamic Range Compression, it works ok and disables/enables My Rating button, it just has a wrong name.
