### ISSUE TITLE
Panel wall modification (10x3)

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#179]
Hi Marcel, this would be a mockup for (10x3).
I wasn't completely sure about the aspect ratio for thumbs that you use (I presumed 2:3).
I also estimated header and footer size.
I can change the mockup if needed!
http://i.imgur.com/lNq03lw.jpg
When you get a chance please let me know if the thumb aspect ratio is ok with you and if I correctly estimated header and footer size.
When that's checked I'll make a mockup for (9x3) when header or footer is disabled.

Btw I could have created this in autocad faster than with corel but unfortunately autocad doesn't use pixels as units :smile:

**Comment by marcelveldt** [comment]
Thanks for the mockup, I'll create it like that.
I renamed the "panel wall" to just panel which will include the header and footer and created a new view "panel wall" which will be, just like "big panel wall" fullscreen without any header or footer.

The aspect ratio to use is 1:0.675

http://www.imdb.com/help/show_leaf?photosspecs

**Comment by marcelveldt** [comment]
This is the end result with your suggestions...
![2016-02-11](https://cloud.githubusercontent.com/assets/6389780/12985771/879783e2-d0f4-11e5-8427-c1851307d6f5.png)

**Comment by marcelveldt** [comment]
and this is the new panel wall view...
![2016-02-11 1](https://cloud.githubusercontent.com/assets/6389780/12985850/d1903ac0-d0f4-11e5-8aa2-b8ac57faff7a.png)

**Comment by vdb86** [comment]
Hi Marcel, this looks amazing!
I still feel like the distance between the thumbnails could be smaller (and the thumbnails themselves bigger)
Let me test it out in corel and send you another mockup (of course if you don't mind).
And I'll take a look at the version with only footer/header.

**Comment by vdb86** [comment]
This should should look even better:
![10x3](https://cloud.githubusercontent.com/assets/13788152/12988431/0049ea94-d101-11e5-9d3e-081f71c4ab13.jpg)

For the new panel wall view, you could increase the size of the thumbnails so that the distance between them is 10px.
That increase in size will yield better looking icons!

**Comment by vdb86** [comment]
I have played around with the version with no Header or Footer.
That's the version with 9x3 layout.
This is the one with one with Header:
Thumb: 196x291
Distance left side-thumb: 46
Distance right side-thumb: 46
Distance header-thumb: 28
Distance bottom-thumb: 29
Horizontal distance thumb-thumb: 8
Vertical distance thumb-thumb: 10

**Comment by vdb86** [comment]
This is the one with Footer only:
Thumb: 196x291
Distance left side-thumb: 46
Distance right side-thumb: 46
Distance top-thumb: 38
Distance footer-thumb: 39
Horizontal distance thumb-thumb: 8
Vertical distance thumb-thumb: 10

**Comment by marcelveldt** [comment]
10x3 panel view with 10px spacing...

![2016-02-11 4](https://cloud.githubusercontent.com/assets/6389780/12993470/9b6442ea-d11a-11e5-892e-b45ae7c57c2c.png)

**Comment by marcelveldt** [comment]
panel wall view with 10px spacing...

![2016-02-11 5](https://cloud.githubusercontent.com/assets/6389780/12993579/42b2dbf6-d11b-11e5-82b1-3e78fd91123a.png)

**Comment by vdb86** [comment]
This looks freakin' awesome...

**Comment by marcelveldt** [comment]
btw, there is no version with 9x3 layout... only with 8x3 layout (big panel wall).
Did you mean that one ?

**Comment by marcelveldt** [comment]
this is big panel wall (8x3) with 10px spacing

![2016-02-12](https://cloud.githubusercontent.com/assets/6389780/12993891/489e7e7e-d11d-11e5-8d41-e8592a291a83.png)

**Comment by vdb86** [comment]
I wouldn't change big panel wall, I thinks it's great as it is.
The 9x3 layout was meant for panel wall (now just panel) without header or footer.
With that layout the skin would use additional free space which was provided by the lack of either header or footer.
To be honest I did this just in case you needed it (wanted to help).
I think that both 10x3 and 10x4 look great.

**Comment by vdb86** [comment]
Just saw the big panel wall with 10px spacing, looks pretty good!

**Comment by marcelveldt** [comment]
OK, I'll keep it like this. Will be includes in next beta too.

Users will btw be able to play with the spacing a bit by changing the unfocused border size (which is 4px by default)

**Comment by vdb86** [comment]
Sounds good Marcel!

**Comment by mgonzales71** [comment]
I've been watching this and just wanted to say I like as well :)

**Comment by vdb86** [comment]
Mario!
Since all three of us are here we can become three musketeers.
Sorry for off topic :)

**Comment by marcelveldt** [comment]
haha, lol

**Comment by marcelveldt** [comment]
I'll close this one for now (so I have better overview in my todo list). Reopen if it needs more work when you reviewed it.

**Comment by vdb86** [comment]
This looks awesome!
Any chance we can disable zoom effect on big panel wall and have the same navigation as on panel?
Basically just moving around the selection square?

**Comment by marcelveldt** [comment]
OK, will fix that

**Comment by vdb86** [comment]
Works perfectly...
