### ISSUE TITLE
Vertical tile menu lost

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#180]
Hi Marcel, while I was testing this beta I noticed that the vertical tile menu is lost.
It is available while choosing the home menu layout, when you select it there is nothing on the home screen where the menu should be.

**Comment by mgonzales71** [comment]
yea I saw glitches in the new vertical menu - it occurs when you have more home menu items then the screen can display at once.

try it with numerous home menu items and then scroll thru the list in a cycle or two and you should see the issue

**Comment by marcelveldt** [comment]
Fixed the vertical home menu with tiles, thanks for the catch.

@mgonzales71 not sure what you mean with the glitches, I tried to reproduce but it seems to be working fine (except for the slow animation)

**Comment by vdb86** [comment]
I tested it with more items than the menu can show and everything works ok on my end.
I'll close this issue.
Thanks Marcel!

**Comment by marcelveldt** [comment]
new beta is online

**Comment by mgonzales71** [comment]
This is what I meant...

This is supposed to be the "Settings" home tile/menu:

![2016-02-14_20-49-00](https://cloud.githubusercontent.com/assets/6510026/13040106/b5465c4a-d35c-11e5-9f46-799eb49b5c38.png)

This is supposed to be "Videos":

![2016-02-14_20-49-37](https://cloud.githubusercontent.com/assets/6510026/13040105/b5463aee-d35c-11e5-90c5-bcdce9089b3d.jpg)

and this "Weather":

![2016-02-14_20-49-49](https://cloud.githubusercontent.com/assets/6510026/13040104/b545a926-d35c-11e5-8d68-532c8941572d.jpg)

hope that helps explain what I meant.  the highlighted menu items doesn't always watch what is shown.

**Comment by vdb86** [comment]
I've tried to reproduce this several times yesterday but was unable, I'll continue testing! :smiley:

**Comment by marcelveldt** [comment]
oh crap, I know what the issue is... @mgonzales71 are you using an aspect ratio of 16:10 instead of 16:9 perhaps ? I think so because the panel behnd the menu is not all the way to the bottom.

I'll see if I can detect the screen's AR to adjust the menu animation

**Comment by vdb86** [comment]
I just tried the current beta on my tablet and I've managed to reproduce what Mario was saying, the panel behind the menu is not all the way down to the bottom.

**Comment by mgonzales71** [comment]
the resolution of my laptop is 1280 x 800 
according to the google - "WXGA is also used to describe a resolution of 1280x800 pixels, with an aspect ratio of 16:10" - so I guess you were on to the culprit!  good catch.  I never bothered to calculate it. hehe
