### ISSUE TITLE
Low power systems

### ISSUE THREAD

**Issue by Glenn-1990** [marcelveldt/skin.titan#182]
The setting for low power systems doesn't seems make much difference.
 What kind of optimizations should it do?

Arm platforms are not rendering the GUI as fast than x86 processors, usually they are even limited to 10 or 5fps by a default setting (rpi,imx,wetek). This makes animations on dialog/window opening horrible, this will never work smooth with 10fps. So is it possible to disable all kind of animation (sliding dialogs/osd and sush) when this setting is enabled? This will definitely increase the usability on arm based systems :-)

**Comment by marcelveldt** [comment]
What I did previously is to replace all slide/bounce animations by a simple fade animation when that setting is enabled. I was testing on a raspberry pi 2 back then and that was working pretty smooth. Should I disable all window animations if the setting is enabled ?

**Comment by Glenn-1990** [comment]
Maybe it's just broken? For example the video osd (when channel switching) slides up from the bottom when this setting is enabled.

**Comment by marcelveldt** [comment]
Oh crap, you're right. I did some rework last week to the OSD and forgot to include this....
Did you see more places where the slide animation is still present ?

**Comment by marcelveldt** [comment]
I have changed this in the most recent version of the skin (new stable version will follow shortly).
I disabled the slide animations if the lowpower setting is enabled.

Let me know if you see any more places that could benefit with this fix.
