### ISSUE TITLE
Big panel wall and Panel wall view on touch device

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#185]
Hi Marcel,
I've tested Big panel wall view on my tablet and this view doesn't use the whole screen.
The upper part is empty (feels like it has a header).
Could we move everything up and add the navigation bar (like with other views) at the bottom?
The panel view has enough space on the bottom, but the navigation menu is not shown.

These are the screenshots:
The Big panel wall:
![screenshot000](https://cloud.githubusercontent.com/assets/13788152/13176615/e764c97c-d713-11e5-877a-eb7f228fd924.png)

The Panel wall view:
![screenshot001](https://cloud.githubusercontent.com/assets/13788152/13176765/ce2560e2-d714-11e5-8c45-bbc3c8daf7af.png)

The Panel view:
![screenshot002](https://cloud.githubusercontent.com/assets/13788152/13176747/b9e79410-d714-11e5-865e-647ed502411a.png)

**Comment by vdb86** [comment]
I saw that with the newest Beta 3.6.32 you've added header to the big panel wall for touch devices, it might be more useful to have navigation in the footer.
Same goes for the panel wall view.

**Comment by marcelveldt** [comment]
Good catch ;-)
I have adjusted this in latest beta. So, whenever the screen's aspect ratio is 16:10 instead of the default 16:9 the extra space is filled with the footer

**Comment by vdb86** [comment]
Can't wait to test it out.
Thanks for all the hard work!
