### ISSUE TITLE
Black screen after update

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#187]
Hi Marcel,
this is not a bug (I guess), just some weird behavior.
After updating Titan Beta I always get a black screen for some time period (couple of minutes) and then the normal screen comes back.
Not completely sure if this is connected to Titan Beta or Skin Helper (since both usually update at the same time).
I've seen this behavior on my RPI2, tablet and laptop.

Is this normal?

**Comment by marcelveldt** [comment]
That is correct, this is default behaviour of Kodi whenever a skin is updating.
It unloads the skin, starts copying the files and loads the updated skin.

So not a bug but by design in kodi ;-)

**Comment by vdb86** [comment]
Sounds good, sorry for the opened issue then :)
