### ISSUE TITLE
Main menu Modern Low Horizontal Big

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#189]
Hi Marcel,
I've noticed that on main menu Kodi logo is shown until weather is loaded.
Could you please add an option to completely remove the logo?
I know there is an option to use a custom image instead of the logo, I'm was hoping to completely disable it.

**Comment by marcelveldt** [comment]
And what should be whoen instead ? Nothing ?

**Comment by vdb86** [comment]
Yes, just the screen, nothing else :)

**Comment by marcelveldt** [comment]
This should already be fixed in recent version of the skin. If not, please re-open this issue.
