### ISSUE TITLE
Paused screen while playing movie

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#190]
Hi Marcel, the pause screen is above autosubs plugin.
When I start a movie and it doesn't have a local subtitle the autosubs plugin kicks in, pauses the movie and opens a window for downloading subtitles.
But the word PAUSED is above it and obstructs the view.

Let me know if you need a screenshot.

**Comment by marcelveldt** [comment]
this should be fixed in the latest beta...

**Comment by vdb86** [comment]
Thank you..
