### ISSUE TITLE
TV Next Up Info?  Also, TV show Season & Episode OSD Info

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#191]
1)

![avorppy](https://cloud.githubusercontent.com/assets/6510026/13380369/2955c154-ddf6-11e5-89c8-5a2001d30374.png)

what happened to the TV Next Up info that used to be displayed in the footer, etc?

shows used to say - new, returning, ended, etc - that seems to be gone now.

2)  Did the OSD Info display use to show the TV show Season and Episode Info?
Oddly - it seems to be gone or did I imagine that?

**Comment by marcelveldt** [comment]
1) It shows the status if the show is not in progress, is shows the next episode date if the show is in progress. Always been that way ;-)

2) I can't remember either. I haven't changed it so maybe it's your imagination ?

**Comment by mgonzales71** [comment]
Hi Marcel...

Thanks for the reply.  wanted to follow back up and add a couple other items as an FYI before I forget.

1) Well If I understand correctly this should show something (the show is in progress) but it is blank - don't think this is now an option in settings is it?

![2016-02-28_12-25-46](https://cloud.githubusercontent.com/assets/6510026/13381703/6e39ca2e-de17-11e5-8883-520ff039dfed.jpg)

2)  I think the Season and Episode info used to be displayed in the Info OSD - I can't find a screenshot but an old PR makes me belive it was - https://github.com/marcelveldt/skin.titan/pull/55

think it would be nice to have either in OSD Info or plot Info?  idk - what do you think?

![2016-02-28_12-50-35](https://cloud.githubusercontent.com/assets/6510026/13381824/6002a41e-de1a-11e5-9519-2ab8b340f2d2.jpg)
 
3) Was entering / leaving weather menu/tile and kodi locked up.
only thing I saw in the log around the time was:

12:27:05 T:12032   ERROR: XFILE::CDirectory::GetDirectory - Error getting $INCLUDE[WeatherWidget]
12:27:05 T:12032   ERROR: Previous line repeats 2 times.

tried to reproduce crash - so far just the error is reproducable 

4) oh and speaking of crashes - durring the last few updates of the skin and helper service the helper script doesn't always stop (so it can be updated) - and twice this crashed Kodi while the skin was being updated and left the skin in a corrupt state - thankfully I take backups.

have you seen this happen ever?

**Comment by mgonzales71** [comment]
possibly related to the weatherWidget error above - saw this also in logs:

16:05:36 T:6828   ERROR: XFILE::CDirectory::GetDirectory - Error getting $INCLUDE[SystemInfoWidget]
16:05:36 T:9356   ERROR: Previous line repeats 2 times.

**Comment by mgonzales71** [comment]
Marcel,

Wanted to follow up with the case of the missing tv next aired info that used to be in the footer.

grabed a copy of the skin and skin helper from git - both dated around Dec 20th 2015.

As you can see - the skin used to display the following next aired info of tv shows in the footer when a tv show was highlighted:

the next date it airs,
a returning show,
a new show,
or 
an ended show.

photos attached below showing what seems to be now missing in the skin.

I am not sure when this stopped working/was changed or if now another skin setting affects this being displayed or ??

Thanks

Mario

![2016-03-11_09-18-24](https://cloud.githubusercontent.com/assets/6510026/13710163/a18d2c96-e76c-11e5-86c3-39e063fb5613.png)
![2016-03-11_09-19-17](https://cloud.githubusercontent.com/assets/6510026/13710164/a18e925c-e76c-11e5-804c-d24162d9a285.png)
![2016-03-11_09-22-55](https://cloud.githubusercontent.com/assets/6510026/13710166/a18fcbea-e76c-11e5-8bfe-09cdfa4029f3.png)
![2016-03-11_09-23-27](https://cloud.githubusercontent.com/assets/6510026/13710165/a18ed320-e76c-11e5-9076-da550f8a32ec.png)

**Comment by marcelveldt** [comment]
I fixed this a while ago, forgot to report back here
