### ISSUE TITLE
FR: view suggestions

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#199]
some suggestions to add some more views, including netflix style

http://forum.kodi.tv/showthread.php?tid=205482&pid=2263254#pid2263254

**Comment by P1X3L8ED** [comment]
Please add mouse & touch support.

Please add the option to turn submenus on at all times in Horizontal mode
(ie: Confluence & Aeon Nox).


Thank you

**Comment by marcelveldt** [comment]
Please report any requests or bug reports on the forums only as it will be easier for me to track...
http://forum.kodi.tv/forumdisplay.php?fid=212

Mouse & touch support is already in the skin, just enable it in the skin settings.
Also you can enable the submenus to Always show in the skin settings.

**Comment by P1X3L8ED** [comment]
Thank you
