### ISSUE TITLE
FR: Navigation missing

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#204]
Hi Marcel, I promised I'll let you know if I find a window that doesn't have navigation (When enable mouse and touch support is turned on).
I've found this one:
When you're looking at the cast (either movie or tv show) and click on a name.
Local results will pop up (if you have that set up) and a list will appear, you can't back out of that list!
You have to choose something to get out.

Also is it possible to choose information on the footer, or disable it?
Currently we can choose style for media/codec info, maybe have an option disable?
Would be cool to be able to disable rating too.
In the end we could end up having just navigation in the footer :)

**Comment by vdb86** [comment]
Hi Marcel!
I've been playing around with the skin and I see that you added an option to have no information in the footer, thanks!

Is it possible to remove the rating too?

**Comment by marcelveldt** [comment]
you can disable the entire footer, did you know about that ?

**Comment by vdb86** [comment]
Yeah I know, but then I loose the navigation buttons I love so much!

**Comment by marcelveldt** [comment]
request moved to trello board:

https://trello.com/b/VPlkyvMp/titan-skin
