### ISSUE TITLE
FR: Option to remove Paused from the screen

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#205]
Hi Marcel!
Could you please add an option to remove Paused from the screen? :)

**Comment by mgonzales71** [comment]
already has the option...

![2016-03-29_11-00-45](https://cloud.githubusercontent.com/assets/6510026/14118272/9cba1d48-f59d-11e5-8460-b3d201b49402.png)

**Comment by vdb86** [comment]
Sorry about that, I didn't figure out what that option was :)
I'll close it out.
Thanks Mario!
