### ISSUE TITLE
tiny cosmetic issue in certain views (large thumbnail)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#206]
Hi Marcel!

just an FYI...

I have not checked all the views but suspect it may be in other views with large thumbnail option

certainly low priority.

Hope all is well with you and yours... 

Mario

![2016-04-08_23-42-44](https://cloud.githubusercontent.com/assets/6510026/14402254/99d44ef6-fde4-11e5-98c8-a2a5d7c98b25.jpg)
![2016-04-08_23-44-39](https://cloud.githubusercontent.com/assets/6510026/14402255/99d468aa-fde4-11e5-9fdd-eb1e69078bf5.jpg)

**Comment by marcelveldt** [comment]
Hi Mario!
Yes, all is fine. Have been very busy lately so now I'm catching up on all the reports/requests for the skin :-)

How are you doing, fine I hope ?

Yes, I spotted this issue yesterday and already fixed it. There will be another skin update later today with a whole bunch of fixes.

**Comment by mgonzales71** [comment]
Yea doing fine here also thanks!

Have a great weekend Marcel :)

Mario

**Comment by marcelveldt** [comment]
Same to you Mario!

The new skin update is now uploading to the beta repo btw
