### ISSUE TITLE
Nominations and file location in video info

### ISSUE THREAD

**Issue by vdb86** [marcelveldt/skin.titan#207]
Hi Marcel!
Haven't talked to you in a while :)
Hope you're doing good!

I've seen a couple of instances with Titan mixing up Nominations between some movies.
Also the file location takes a while to show and refresh when you check out some other movie.

This is happening with the current version of Titan, I haven't tried it with Beta version.

**Comment by marcelveldt** [comment]
The nomations stuff should be fixed a while back.
The file info stuff is somthing I just fixed. Available in next skin update
