### ISSUE TITLE
Kodi Favourites as Widget Rows

### ISSUE THREAD

**Issue by oswald8** [marcelveldt/skin.titan#208]
Hello! 

Firstly I would like to thank you for the titan skin, it is my favourite one!

I have been trying to add the "Kodi Favourites" as a widget row using the "Netflix style homemenu layout 2" in hopes of having it display only a single row of squares of my favourite apps to make it as minimalistic as possible.

Visually this works, but then when I click on one of the widget row item (Youtube for example), it does not go straight to the Youtube menu, it seems to want to load the side menu first and then it loads up the youtube menu properly. I hope I am making sense! Am I doing something wrong, is there a way around this?

Thank you for your time!

Cat
![menu](https://cloud.githubusercontent.com/assets/18509327/14585134/1a577118-041e-11e6-9a64-9c715717a56e.png)

**Comment by marcelveldt** [comment]
Does this issue still exist on the most recent version of the skin ?

**Comment by oswald8** [comment]
Yes the issue was resolved with the newest version of the skin, thanks so much for your time.

**Comment by Adamcj** [comment]
Oswald, I've been trying exactly what you've managed to do. How did you manage to get a widget filled with favourites? My only work around has been using an add on (such as super favourites) and then creating a widget off of that? Thanks Adam
