### ISSUE TITLE
in case you like... few texture updates: modern rounded toggle + weather alert icon

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#210]
Hello Marcel!

Forgot to send these to you when I first saw your new rounded modern theme option.

![radio-button-fo](https://cloud.githubusercontent.com/assets/6510026/14938738/a3dbe7ce-0ee2-11e6-88d9-f98540dc2bbb.png)
![radio-button-nf](https://cloud.githubusercontent.com/assets/6510026/14938739/a3dc45ac-0ee2-11e6-8304-4099b63c0cc8.png)

Also - a while back I was playing around with an icon to show in the header when weather alerts are displayed:

![weather_alert_3](https://cloud.githubusercontent.com/assets/6510026/14938756/37a37a4e-0ee3-11e6-8a38-4c311718910c.png)

Along that same line - was thinking that since it is so easy to miss a weather alert popup that maybe if an alert is in effect display a bold ! in red in header and Video Info of the weather displays to alert the user to open weather and check/read the alert(s).

Something like this?

![2016-04-30_15-04-37](https://cloud.githubusercontent.com/assets/6510026/14938812/7dc4858e-0ee5-11e6-96a6-5b55057740ac.jpg)

btw - saw you added weekend and 36 hour weather info.  i like! :)

As always feel free to use any of these textures if you like them.

Have an awesome weekend!

Mario

**Comment by mgonzales71** [comment]
And an alternate of the version above:

![radio-button-nf](https://cloud.githubusercontent.com/assets/6510026/14968279/d6ee86fa-1070-11e6-88d8-6ad476332485.png)
![radio-button-fo](https://cloud.githubusercontent.com/assets/6510026/14968280/d6eeb800-1070-11e6-96cf-1dfd0ee32449.png)

**Comment by mgonzales71** [comment]
found more choices hehe 

![alt-switch-off](https://cloud.githubusercontent.com/assets/6510026/15219933/70fd18aa-181a-11e6-8685-9fc99849eeee.png)
![alt-switch-on](https://cloud.githubusercontent.com/assets/6510026/15219934/7101800c-181a-11e6-85a6-2b3806aa4ad5.png)
![ios7_style_off](https://cloud.githubusercontent.com/assets/6510026/15219935/7102a46e-181a-11e6-94bf-40ec4b132a86.png)
![ios7_style_on](https://cloud.githubusercontent.com/assets/6510026/15219936/710534fe-181a-11e6-86ea-702cf2596c5d.png)

**Comment by marcelveldt** [comment]
Hey Mario, can you wrap these in a pull request please to the master branch ?
currently moving over all requests from github issues list to the new trello board.
