### ISSUE TITLE
proposed change for Startup.xml

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#215]
Howdy Marcel!

Wanted to make a suggested change for **Startup.xml**

download link: http://pastebin.com/raw/qwL2jn97
view link: http://pastebin.com/qwL2jn97

code addition snippet (insert starting at line 8 of Startup.xml)
```
		<control type="image">
			<width>100%</width>
			<height>100%</height>
			<aspectratio>keep</aspectratio>
            <texture>$INFO[Skin.String(SplashScreen)]</texture>
			<visible>Skin.String(SplashScreen) + IsEmpty(Skin.String(AutoStartPlayList))</visible>
		</control>
```

reason for suggesting this:

currently the Kodi default Splash.png or user's profile/media/Splash.png will display briefly followed by a black screen that can last for a few seconds before the helper script kicks in and displays either the user's custom playlist item or custom splash screen defined in skin settings.

this change will display the users custom spash image earlier *(if defined and not a playlist)

I have not found a way to disable the momentarty display of the default Kodi Splash.png (or user's /profile/media/Splash.png if it exists to override the default) - don't think you can usless you _add / change_ the following to the users **advancedsettings.xml** file:
```
<splash>flase</splash>
```

Q: can your helper script make changes to **advancedsettings.xml** ? 

If it can you may want to consider having it toggle / add (or create and add) that directive to the xml file for an even cleaner custon skin startup.

but I would be happy with just this small change to **Startup.xml** since I can make the change to **advancedsettings.xml** myself.  (I suppose you could display a popup or put a note under the skin setting suggesting the user do this)

Finally - Just in case you liked either (or both) here are my custom splash and custom default background images that I use:

**custom splash**
![alt titan custom splash](https://cloud.githubusercontent.com/assets/6510026/15582299/16182978-2325-11e6-9a0f-9015dab2bceb.jpg)

**custom default background**
![alt titan custom bg](https://cloud.githubusercontent.com/assets/6510026/15582302/19f9c132-2325-11e6-8bd5-82774912a3ed.jpg)

feel free to use them for your own setup or in the skin if you are so inclined :smile:

Thanks,

Mario

- 5/30 updated links, code - had unbalanced ")"

**Comment by marcelveldt** [comment]
Thanks for the fix Mario, I will add it in tonight.
As for the question about modifying the advancedsettings.xml. No, Kodi scripts are not supposed to modify system files. Yes, it's technically possible but that will violate the rules.
