### ISSUE TITLE
Titan Beta 3.6.69 - Label Formating: $VAR[SquareThumb] is not defined

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#218]
11:07:52 T:9984 WARNING: Label Formating: $VAR[SquareThumb] is not defined

Affecting Widgets and and Square Panel and Square Panel Details Views.

![2016-06-06_11-15-15](https://cloud.githubusercontent.com/assets/6510026/15832648/fc46b1de-2bd7-11e6-9808-17a5096872ea.png)
![2016-06-06_11-11-58](https://cloud.githubusercontent.com/assets/6510026/15832628/e44cca50-2bd7-11e6-91da-d905005bdbb4.jpg)
![2016-06-06_11-12-13](https://cloud.githubusercontent.com/assets/6510026/15832629/e45069d0-2bd7-11e6-9bef-fb2ad01e5ba0.png)

**Comment by marcelveldt** [comment]
Sorry for the late reply Mario. I do not check any messages at here very often.
This particular issue has been fixed already. Thanks anyway for reporting.
