### ISSUE TITLE
[krypton] skin items 

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#227]
noticed a few Krypton related items - created this Issue to help track the ones I have noticed (and have not but you may have?) :smile:

- [x] Addon.xml - assets tag (screenshots, etc)
 http://forum.kodi.tv/showthread.php?tid=250862&pid=2376263#pid2376263

- [x] DialogAddonInfo
 http://forum.kodi.tv/showthread.php?tid=250862&pid=2360647#pid2360647
 
- [x] DialogPlayerProcessInfo.xml
 http://forum.kodi.tv/showthread.php?tid=250862&pid=2384183#pid2384183
 
- [x] and for some reason they decided to rename LibrarySettings to MediaSettings
http://forum.kodi.tv/showthread.php?tid=250862&pid=2384817#pid2384817

anyway - I am sure there are others - just added the ones I noticed while testing the latest kodi krypton alpha + titan skin (beta)

**Comment by mgonzales71** [comment]
Hey Marcel,

Hope you and your family are doing well

Decided to take a crack at 

DialogPlayerProcessInfo.xml

http://pastebin.com/Fa9CgB5g

Also IncludesVariables.xml needs the following added:
```
	 <variable name="VideoHWDecoder">
 		<value condition="Player.Process(videohwdecoder)">Hardware</value> <!-- localize string -->
 		<value>Software</value> <!-- localize string -->
 	 </variable>
```

Note: 

Right now lables are hard coded english since I haven't yet searched for existing localized string values (or added missing ones)

Couple of screenshots (used DemoPVR since I don't have a tuner/dvr):

![2016-08-10_04-10-31](https://cloud.githubusercontent.com/assets/6510026/17551902/8b4f3b9c-5eb1-11e6-9da6-aeeb73005dbe.png)

![2016-08-10_04-10-39](https://cloud.githubusercontent.com/assets/6510026/17551906/8f106e86-5eb1-11e6-8d57-291bd6b75edd.png)

Not sure about the use of buttons with the -5 item gap - was trying to go for a "tab" look.. plus I wanted to try out the new auto width :smile: 

let me know what you think.

Thanks,

Mario

**Comment by mgonzales71** [comment]
![2016-08-10_04-30-27](https://cloud.githubusercontent.com/assets/6510026/17552201/49ad4be6-5eb3-11e6-873c-baad861d2ae5.png)

(forgot a screenshot - this shows movie playback with the playerprocessinfo, plot and info display visible)

**Comment by marcelveldt** [comment]
Hi Mario! Yes, all doing great here. Having our holidays now so just enjoying the quality time with the family. Hopefully the weather will be better next days because so far it was not that great.

You're also doing fine ?

Thanks for your work on this! Would it be possible to do a PR for this on the Krypton branch ?
If not I'll merge in the changes myself.

The language ID's to use can be found in the language resource addon, with hardcoded strings the repo submission will be denied. If you do not have time for the language ID's I'll take a look at it myself next week.

**Comment by mgonzales71** [comment]
I just upgraded my windows 10 to the big anniversary update and it broke my SourceTree / GitHub environment - I am going to work on getting that back up and working today and then I can manage PR's etc :smile:  

And I know about the language ID's that is why I placed all those reminder comments so I knew where to update the code when I had time to search the Kodi built in ID's and then add the missing ones to the skin.

Yea - doing well here also :smile: glad that you are too!

Awww yes - I am guessing you mean "holiday(s)" (in European sense) he he

Over here when everyone at work is off for a day(s) it's a "holiday" but if you are off but most everyone else has to work that is a "vacation"  - and we get a lot less "vacation" then most of the more "advanced" nations of the world LOL I am jealous!

Well have fun - hope you get some good weather - it's been HOT here the last couple weeks after a nice mild July - I am already tired of the 90+ :fire: temps here. 

If all goes well I should get you a PR in a day or so.

Mario

**Comment by marcelveldt** [comment]
Yes, it's vacation indeed. I have 3 weeks of vacation this year. Already 2 weeks have passed and the weather was really crap. lot's of rain and cold temperatures. Luckily since yesterday the rain stopped and the temperature is rising above the 20 degrees celcius.

Hope you can get your system running again. I plan to fix the latest Krypton changes in next couple of days.

Thanks as always for your help.

**Comment by mgonzales71** [comment]
Got the PR done for DialogPlayerProcessInfo - https://github.com/marcelveldt/skin.titan/pull/229

**Comment by marcelveldt** [comment]
the addon.xml is now updated for krypton, also incorporated the new changes to the addoninfo dialog.
only thing todo some day is create some new screenshots (in master branch) because the current ones are really outdated

**Comment by mgonzales71** [comment]
i saw that - very nice!

once the skin has stabelized and kryton is at least to RC stage it probably will be safe to add new screenshots then!

I had a suggestion for changes to "settings" for the skin since so much has changed for Krypton.

Something like the following (would make touch users happy with larger targets) - something I didn't mock up but will also suggest is that settings buttons be increased in "height" for the same reason (touch users):

icons replacing current background (well landscape image):

![2016-08-19_17-16-56](https://cloud.githubusercontent.com/assets/6510026/17827549/770b3c88-6633-11e6-8ee0-60df9989a918.png)

or making the existing (or new) landscape image a fullscreen background in addition the icon buttons:

![2016-08-19_17-16-56 a](https://cloud.githubusercontent.com/assets/6510026/17827554/7de61212-6633-11e6-96e9-76998dca92d5.png)

**Comment by mgonzales71** [comment]
Marcel,

was playing around with a new skin "Theme" (as in textures) 

here is the xbt file for the one I have been playing around with - goal is to add a little subtle "texture" to the textures in the skin LOL

more of a WIP for fun thing I was doing for personal amusement but curious what you think 

https://onedrive.live.com/redir.aspx?cid=599da6bd82779e65&resid=599DA6BD82779E65!7466&parId=599DA6BD82779E65!4605&authkey=!AJlacGJOzfy1zps&ithint=file%2cxbt

FYI - based off textures for krypton rev of the skin

mario
