### ISSUE TITLE
Settings Artwork Update 

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#235]
For your consideration:

![screenshot016](https://cloud.githubusercontent.com/assets/6510026/18276231/f0c51304-73fe-11e6-9d21-ba96bebcc242.png)

Possible new artwork for use with the new settings panel/window (Upper left thumb)

**System Info**

![system_info](https://cloud.githubusercontent.com/assets/6510026/18276189/c597bad8-73fe-11e6-8fe6-8d3ac5e491b7.jpg)

**Add ons**

![addons](https://cloud.githubusercontent.com/assets/6510026/18276188/c597a2c8-73fe-11e6-8386-d45b88408eef.jpg)

**Interface**

![interface](https://cloud.githubusercontent.com/assets/6510026/18276187/c5976308-73fe-11e6-8fc3-4ae14ac8079f.jpg)

**Live TV**

![live_tv](https://cloud.githubusercontent.com/assets/6510026/18276190/c597cb04-73fe-11e6-94de-6d275e22b1fa.jpg)

**Media Settings**

![media_settings](https://cloud.githubusercontent.com/assets/6510026/18276191/c59876ee-73fe-11e6-8f99-6c591e876461.jpg)

**Player Settings**

![player_settings](https://cloud.githubusercontent.com/assets/6510026/18276184/c593fe2a-73fe-11e6-88cc-943eb4edb451.jpg)

**Profiles**

![profiles](https://cloud.githubusercontent.com/assets/6510026/18276186/c596dfe6-73fe-11e6-9241-3230a7dd4d15.jpg)

**Services**

![services](https://cloud.githubusercontent.com/assets/6510026/18276185/c5945e38-73fe-11e6-9118-fbac4fb9ce05.jpg)

**Skin Settings**

![skin_settings](https://cloud.githubusercontent.com/assets/6510026/18276192/c5ab17c2-73fe-11e6-9616-5f8d149afe02.jpg)

**System**

![system](https://cloud.githubusercontent.com/assets/6510026/18276193/c5ca5c2c-73fe-11e6-8a43-442302e04f7d.jpg)

**Comment by mgonzales71** [comment]
ran the images above thru tinyjpg.com to reduce and optimize them (see attached zip below)

[optimized.zip](https://github.com/marcelveldt/skin.titan/files/457934/optimized.zip)

**Comment by mgonzales71** [comment]
created a PR for Krypton branch so you can easily merge if you do like.

if not please suggest changes, or pass/close the PR, etc.

PR - https://github.com/marcelveldt/skin.titan/pull/237

Hope you like :smile:

**Comment by mgonzales71** [comment]
and PR #238 for Jarvis update too if you approve

**Comment by marcelveldt** [comment]
I Like it Mario, thanks for your hard work.
I haven't been around much lately because of the summer so it's good to see that you still want to help me out.

FYI: I've added you as author of the skin.
