### ISSUE TITLE
FR: open trailers in preview window

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#72]
http://forum.kodi.tv/showthread.php?tid=205482&pid=2015762#pid2015762

**Comment by mgonzales71** [comment]
you could integrate this with this FR - https://github.com/marcelveldt/xbmc.skin.titan/issues/31

**Comment by marcelveldt** [comment]
for now I've added a dialog in the video info screen in which you can choose from the available YouTube trailers. This won't close the videoinfo screen (so it wont kick you out of the addon and into YouTube)

**Comment by marcelveldt** [comment]
http://forum.kodi.tv/showthread.php?tid=205482&pid=2077210#pid2077210

**Comment by marcelveldt** [comment]
Maybe add extra setting to choose what to do when playing trailers:
- open in window
- open in background
- close videoinfo and play fullscreen

Currently trailers are always shown in the background. Maybe this should by default play in a dialog which can be clicked to go fullscreen.

**Comment by vdb86** [comment]
I like the idea of having extra setting, everyone is able to choose what they prefer.
Awesome!

**Comment by marcelveldt** [comment]
added options to select default trailer playback mode
