### ISSUE TITLE
FR: Option to Replace Date/TimeInfo with NowPlaying (videowindow)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/skin.titan#87]
what do you think of something like this:

notice now playing video in upper right hand corner (replacing date and time)

my reasoning for the request is that I am often in other parts of the skin but want to keep watching what is playing without pausing playback.

having the video as the background is not something I find useful for this.

![2015-06-08_06-37-10](https://cloud.githubusercontent.com/assets/6510026/8036087/1da26d34-0daa-11e5-8990-7819d857b845.jpg)

was able to do a little test with this rough, unfinished code in the following files:

hopefully you get the idea of what I was thinking for this quick and dirty test...

home.xml

		
		<control type="group">
			<animation effect="slide" end="-20" time="0" condition="Skin.HasSetting(HideWidgetPanelBackground) + Skin.String(GadgetRows, enhanced)">Conditional</animation>
			<include condition="!Player.HasVideo">TimeInfo</include>
			
			<control type="videowindow">
                <posx>1519</posx>
                <posy>-30</posy>
                <width>356</width>
                <height>200</height>
                <aspectratio>keep</aspectratio>
				<visible>[Player.HasVideo + Skin.HasSetting(NowPlayingReplacesTimeInfo)]</visible>
			</control>
		</control>
		
includes.xml

	<include name="TimeInfo">

        <control type="group">
            <visible>![ControlGroup(77777).HasFocus | StringCompare(Window(Home).Property(ShowWidget),show)]</visible>
			<visible>!Control.IsVisible(881)</visible>
			<visible>!Control.IsVisible(77551)</visible>
			<visible>[Player.HasVideo + Skin.HasSetting(NowPlayingReplacesTimeInfo)]</visible>
			<control type="videowindow">
                <posx>1519</posx>
                <posy>-30</posy>
                <width>356</width>
                <height>200</height>
                <aspectratio>keep</aspectratio>
			</control>
		</control>

couple more screenshots of this mod in action:

![2015-06-08_06-52-09](https://cloud.githubusercontent.com/assets/6510026/8036179/0e6311c4-0dab-11e5-800d-a0a541307ce4.jpg)
![2015-06-08_06-52-31](https://cloud.githubusercontent.com/assets/6510026/8036178/0e6273e0-0dab-11e5-9cab-4dc78a2bb58b.png)

**Comment by mgonzales71** [comment]
Actually have it working implicitly in the following mod if Disable Now Playing in Background is true: 

http://pastebin.com/dL5LQ1Pe

look under the TimeInfo include section - I have tested it and works pretty well so far - lines up nicely with the existing Now Playing Banner when out of Full Screen during playback even.

Would need to add the skin setting logic to fully enable it properly of course.

If you were to go with this as a feature....   would you want to change the setting to something like:

Show Now Playing when outside of Full Screen video playback:

Disabled | In Background | In place of Time and Date  
(as 3 options you cycled through in settings)?

**Comment by mgonzales71** [comment]
even plays nice with the mute indicator 

![2015-06-09_13-53-06](https://cloud.githubusercontent.com/assets/6510026/8069390/1128b878-0eaf-11e5-9905-e0422f9613a1.jpg)

**Comment by marcelveldt** [comment]
Hi Mario,

I'm okay with this mod, as long as it is configurable :-)
Your suggestion of using a toggle with three options is very nice.

The setting should then be called "Display Now Playing video preview" ?

BTW: It's better if you use replace <posx> with <right> to align the control x pixels from the right, that would better line up with the changing aspect ratio of the control. That way you would be sure it is perfectly aligned at the right of the screen.

Also, the setting should not be visible when the theme is set to classic because the classic theme includes this preview by default.

Do you want me to put it in the skin some day or are you going to do a PR for this ?

**Comment by mgonzales71** [comment]
I can look at this weekend unless you get to it sooner :smile:

**Comment by marcelveldt** [comment]
If you want to do it it's fine with me ;-)

So this is what it will be:

- the setting "Disable the Now Playing background" will be renamed to "Display Now Playing video preview". That setting will have 4 options: 
1) Disabled
2) In background
3) In header
4) In header + in background

Please let me know if you want me to do something for this, else I'll wait for your PR :-)

BTW: please check out latest git, I've done a full rewrite of the helper script/service for more speed and stability

**Comment by mgonzales71** [comment]
I haven't had a chance to finish it this weekend - sorry.

Since you are more the expert I will let you go ahead and do it - unless you are busy.

I was having trouble with the scaling and alignment/position of the video window plus the right combo of visible statements :-)  

I am getting ready to go grab the latest GIT and give it a test now.

**Comment by mgonzales71** [comment]
i am going to close this - the player controls work fine as a replacement for this.

btw as of jarvis the default keymap for player control has changed from "m" to "control + n"
